### ISSUE TITLE
Heating climate without data

### ISSUE THREAD

**Issue by augi** [BenPru/luxtronik#17]
The `climate.luxtronik2_domestic_water` entity shows this nice graph ❤️ 
![image](https://user-images.githubusercontent.com/273052/192508339-dd468f05-8bc2-4958-8dbe-f5c11d2f0ed8.png)

Unfortunately, the `climate.luxtronik2_heating` entity looks like being without data 😢 

![image](https://user-images.githubusercontent.com/273052/192508689-a98f7f36-4bf1-4e5d-a148-5c00472a315b.png)

Don't you please know what could be wrong? Also, please note that all the statuses (e.g. `sensor.luxtronik2_status`) and temperatures get the right data.

**Comment by scaronni** [comment]
Just a note, the above merge request does not fix it for me, I have roughly the same issue with something weird on the heating target temperature after updating the integration:

![image](https://user-images.githubusercontent.com/1983966/201695975-92d47025-b9a6-4ee0-b7b8-1594235725fe.png)

**Comment by scaronni** [comment]
I've just noticed that now instead of picking up the set temperature (in my case 21 degrees) it now picks the temperature correction. This is visibile also directly from the entity `climate.luxtronik_heating` which no longer displays the wanted temperature:

![image](https://user-images.githubusercontent.com/1983966/201715104-3b1aeac4-074c-47be-bd43-40845695e474.png)

**Comment by rhammen** [comment]
> I've just noticed that now instead of picking up the set temperature (in my case 21 degrees) it now picks the temperature correction. This is visibile also directly from the entity `climate.luxtronik_heating` which no longer displays the wanted temperature:
> 
> ![image](https://user-images.githubusercontent.com/1983966/201715104-3b1aeac4-074c-47be-bd43-40845695e474.png)

Previously, you could change the heating target temperature with the climate control, but it didn't actually change anything on the Luxtronik. In order to get to a real climate-control, I needed to pick a sensor that controls the temperature of the heatpump. For me, the main sensor to choose was therefore the temperature correction.
Do you know another sensor that can be used to control the heating behavior of the heatpump, but better 'reflects' the heating target temperature?

**Comment by rhammen** [comment]
> Just a note, the above merge request does not fix it for me
> 
> ![image](https://user-images.githubusercontent.com/1983966/201695975-92d47025-b9a6-4ee0-b7b8-1594235725fe.png)

The "heating current temperature" will show the value of the sensor that you configured. 
In your graph, no "Heating current temperature" line is visible. My hypothesis would be that you did not configure which sensor to display.
What sensor did you enter when you select "configure" on the integration? 
I used sensor.luxtronik2_room_temperature to use the RBE room temperature sensor. If you don't have a RBE wall unit, you must select another sensor that reflects the current room temperature.

**Comment by scaronni** [comment]
> Previously, you could change the heating target temperature with the climate control, but it didn't actually change anything on the Luxtronik. In order to get to a real climate-control, I needed to pick a sensor that controls the temperature of the heatpump. For me, the main sensor to choose was therefore the temperature correction. Do you know another sensor that can be used to control the heating behavior of the heatpump, but better 'reflects' the heating target temperature?

Ok I was not aware of this, I did not change the target temperature since integrating the Heat Pump in home assistant, so I never noticed it did not do anything. I understand the point but is now completely confusing. In my opinion it was better before.

I've added the room sensor id to the configuration, so of course now I get this:

![image](https://user-images.githubusercontent.com/1983966/201865148-b1ed3d5e-68e1-4918-8fc9-af566e56ffb1.png)

And the "-1" is both the adjustment temperature and the "target temperature", which does not match at all with the description. It looks like the temperature being read is just wrong. In both current and previous case you could still adjust with `luxtronik2_heating_temperature_correction`.

**Comment by rhammen** [comment]
I agree the naming now is confusing.
To reduce the confusion we should rename "Heating targer temperature" into "Heating target correction".

Do you have an RBE wall-unit that allows you to set the target room temperature?

**Comment by scaronni** [comment]
Unfortunately no. Bought this house in 2020, heatpump was already installed. I updated the firmware myself, reconfigured stuff, tuned, brought network to the Luxtronik controller. etc. but it's still far from being manageable.

`Rant mode on`
The included web interface is a joke, very limited, the frontpage-inspired heatpump24 portal is just terrible, the app sucks. In these 3 different interfaces I can configure different things but not everything in one place. At this point, I would say this home assistant integration lets me do more than these 3 combined, barring for schedule (with negative schedule on the controller for warm water, but not reflected in the app/heatpump24, go figure)
`Rant mode off`

This friday I have appointment with a technician for a check and I will ask if I can upgrade the controller to something less stupid, a room sensor and let me check power consumption through the home assistant integration (https://github.com/BenPru/luxtronik/issues/18) as I'm trying to squeeze in the consumption with my Tesla powerwalls / Enphase solar installation.

**Comment by scaronni** [comment]
> My hypothesis would be that you did not configure which sensor to display. What sensor did you enter when you select "configure" on the integration? I used sensor.luxtronik2_room_temperature to use the RBE room temperature sensor. If you don't have a RBE wall unit, you must select another sensor that reflects the current room temperature.

Can we have the maybe-installed RBE sensor as the default pre-filled in the field when configuring the integration? Or in the text above.

**Comment by BenPru** [comment]
> > My hypothesis would be that you did not configure which sensor to display. What sensor did you enter when you select "configure" on the integration? I used sensor.luxtronik2_room_temperature to use the RBE room temperature sensor. If you don't have a RBE wall unit, you must select another sensor that reflects the current room temperature.
> 
> Can we have the maybe-installed RBE sensor as the default pre-filled in the field when configuring the integration? Or in the text above.

I have added this as pre filled default.

**Comment by scaronni** [comment]
Many thanks!

**Comment by Kars-de-Jong** [comment]
I think the current HA thermostat implementation is not suitable for heating systems where you can only adjust the control loop. It expects a target temperature, not a correction.

**Comment by augi** [comment]
Hello, please note I have the same issue as @rhammen , so after updating to the latest version of HA integration, the `Heating target temperature` went to `0` 😢 
![image](https://user-images.githubusercontent.com/273052/203362885-ff1da2d3-8af8-4bf0-a7f2-ffd48d1cb874.png)

**Comment by rhammen** [comment]
> Hello, please note I have the same issue as @rhammen , so after updating to the latest version of HA integration, the `Heating target temperature` went to `0` 😢 ![image](https://user-images.githubusercontent.com/273052/203362885-ff1da2d3-8af8-4bf0-a7f2-ffd48d1cb874.png)

To be clear: I changed this in the code, and on purpose 😃 
I did this because previously you could change the value, but it did not change anything on the heatpump. 
That felt like not being really usefull... 😄 

In the current implementation, if you change it to a value > 0, the heatpump will (should?) increase the water tempeature. 
And similarly it will (should?) decrease the water temperature if you change it to a value < 0. 
So now the "dial" does function, but as a "temperature correction", not as a "target temperature".

I agree this is different as before and confusing,  and I will try to turn it into a functioning thermostat, based on a "target temperature".
I hope to have something for a "beta-test" in the next couple of weeks.
If you want to comment / discuss its implementation, let's do it in issue #3

**Comment by augi** [comment]
So if I understand it correctly, the _thermometer panel for heating_ is not finished yet, and will be finished as part of #3, so we could close this issue, right?

**Comment by rhammen** [comment]
> So if I understand it correctly, the _thermometer panel for heating_ is not finished yet, and will be finished as part of #3, so we could close this issue, right?

I understood this Issue as being: "Heating current temperature" line does not show, and "Heating heating" does not show.
That has both been fixed, BUT...
.. you need to configure which temperature sensor to show!
In your graph there is still no line for "Heating current temperature" and "Heating heating", which suggest you didn't configure a temperature sensor. 
You need to go to Settings-->Devices-->Integrations, and press "Configure" on the Luxtronik tile. There you enter the sensor to use as "Room temperature sensor". If you have a wall-unit, you can use 'sensor.luxtronik2_room_temperature' (without '''). If you don't have a wall-unit, you will have to enter another sensor temperature sensor.
Once configured, the graph should be similar to the domestic heating graph you showed in your first post.
Because this part has been fixed, I think this issue can be closed.

The "Heating target temperature" does show, but is currently implemented as "Heating correction"., which is confusing.
I intend to change that in the future as part of #3

**Comment by augi** [comment]
Thank you very much, I wasn't aware of this option. I entered there `sensor.luxtronik2_flow_out_temperature_target` (because I don't have a room temperature sensor yet) and its value is shown on the panel, and also the `Heating heating` is shown 🎉
