### ISSUE TITLE
Double code in const.py and xxx.py

### ISSUE THREAD

**Issue by Crashman1983** [BenPru/luxtronik#35]
Sensors for example are partly doubled within const.py and sensors.py This is error-prone and maintenance-intensive. What's the reason for it?

**Comment by BenPru** [comment]
Oh yes, the part in const was a try to fulfill the ha core requirements and provide this hacs module as ha module.
In the next time I will try to move the const part in a seperate branch for "future use".

**Comment by Crashman1983** [comment]
Why did they not accept it? What has to be done to make it an official integration?

**Comment by BenPru** [comment]
> Why did they not accept it? What has to be done to make it an official integration?

See the comments from frenk: [Add new integration luxtronik](https://github.com/home-assistant/core/pull/59788#top)
#59788

- [ ] This integration would benefit from using SensorEntityDescriptions instead of passing in all the info.
- [ ] I would recommend to rebase this PR onto the latest dev before continuing development on this integration.
- [ ] Allow more than one instance of the integration --> #16 
- [ ] Every pull request can only contain one platform (sensor, binary_, ...)

- [ ] Translations should not be an integration task

But the sensor names currently could not translated with home assistant himself!

Many things... :-(

**Comment by Kars-de-Jong** [comment]
Translation is done through Localise, see [Contributing Translation](https://developers.home-assistant.io/docs/translations). That's why they shouldn't be included in your PR.

**Comment by BenPru** [comment]
Should be fixed in the future with the [new integration](https://github.com/BenPru/luxtronik/tree/core-preview).
